AWSTemplateFormatVersion: "2010-09-09"
Description: "Provisions a DB instances with credentials resolved from the SecretManager and deploys it into a private subnet in the ${applicationName}-VPCStack-${environmentName}. A policy is created to allow users to connect to the RDS through IAM"

Parameters:
  # note: applicationName is used to pull the correct secret
  applicationName:
    Type: String
    Default: InnoLab
  environmentName:
    Type: String
    Default: Dev
  # Stack Dependencies
  vpcStack:
    Type: String
    Default: InnoLab-VPCStack-Dev
  userStack:
    Type: String
    Default: InnoLab-UserStack

Resources:
  CredentialsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub "${applicationName}-credentials"

  PostgresRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${applicationName}-Database-${environmentName}
      AllocatedStorage: 100
      DBInstanceClass: db.t3.micro
      Engine: "postgres"
      MasterUsername: !Sub "{{resolve:secretsmanager:${applicationName}-${environmentName}-dbUsername:SecretString}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${applicationName}-${environmentName}-dbPassword:SecretString}}"
      BackupRetentionPeriod: 7
      MultiAZ: false
      AutoMinorVersionUpgrade: true
      StorageType: gp2
      PubliclyAccessible: false
      StorageEncrypted: true
      CopyTagsToSnapshot: false
      MonitoringInterval: 60
      EnableIAMDatabaseAuthentication: true
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      DeletionProtection: false
      DBSubnetGroupName: 
        Fn::ImportValue: !Sub ${vpcStack}-DatabaseSubnetGroup
      VPCSecurityGroups: 
        - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
      MaxAllocatedStorage: 1000
      MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
      Tags: 
        - Key: Environment
          Value: !Ref environmentName
  
  DatabaseConnectPolicy:
    Type: AWS::IAM::Policy
    Description: Policy to allow users to connect via AWS CLI
    Properties:
      PolicyName: !Sub ${applicationName}-${environmentName}-db-connect-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RepositoryPermissions
            Effect: Allow
            Action:
              - "rds-db:connect"
            Resource: 
              # NOTE: db-QJLKM6XPHWPIA2MO6QTDQAGNHQ is a regional variable and does not change unless the region is changed.
              - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:db-QJLKM6XPHWPIA2MO6QTDQAGNHQ/{{resolve:secretsmanager:${applicationName}-${environmentName}-dbUsername:SecretString}}"
      Users:
        - Fn::ImportValue: !Sub "${userStack}-Ian"
        - Fn::ImportValue: !Sub "${userStack}-Grant"
        - Fn::ImportValue: !Sub "${userStack}-Thomas"
        - Fn::ImportValue: !Sub "${userStack}-Peter"
        - Fn::ImportValue: !Sub "${userStack}-Tariq"
    DependsOn:
      - PostgresRDS

Outputs:
  RDSEndpoint:
    Value: !GetAtt PostgresRDS.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RDSEndpoint