AWSTemplateFormatVersion: "2010-09-09"
Description: "Provisions a DB instances with credentials resolved from the SSM parameter store and deploys it into a private subnet in the CCC-VPCStack-${environmentName}."

Parameters:
  applicationName:
    Type: String
    Default: InnoLab
  environmentName:
    Type: String
    Default: Dev
  # Stack Dependencies
  vpcStack:
    Type: String
    Default: InnoLab-VPCStack-Dev

Resources:
  PostgresRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub CCC-Database-${environmentName}
      AllocatedStorage: 100
      DBInstanceClass: db.t3.micro
      Engine: "postgres"
      MasterUsername: !Sub "{{resolve:secretsmanager:${environmentName}-dbUsername:SecretString}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${environmentName}-dbPassword:SecretString}}"
      BackupRetentionPeriod: 7
      MultiAZ: false
      AutoMinorVersionUpgrade: true
      StorageType: gp2
      PubliclyAccessible: false
      StorageEncrypted: true
      CopyTagsToSnapshot: false
      MonitoringInterval: 60
      EnableIAMDatabaseAuthentication: true
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      DeletionProtection: false
      DBSubnetGroupName: 
        Fn::ImportValue: !Sub ${vpcStack}-DatabaseSubnetGroup
      VPCSecurityGroups: 
        - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
      MaxAllocatedStorage: 1000
      MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
      Tags: 
        - Key: Environment
          Value: !Ref environmentName
  
  DatabaseConnectPolicy:
    Type: AWS::IAM::Policy
    Description: Policy to allow DBAdmin to connect via AWS CLI
    Properties:
      PolicyName: !Sub ${environmentName}-db-connect-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RepositoryPermissions
            Effect: Allow
            Action:
              - "rds-db:connect"
            Resource: 
              - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${PostgresRDS}/{{resolve:secretsmanager:${environmentName}-dbUsername:SecretString}}"
      Users:
        - ian.mcnutt
        - matt.alston
        - grant.moore
        - thomas.klock
        - peter.cofrancesco
        - tariq.islam

Outputs:
  RDSEndpoint:
    Value: !GetAtt PostgresRDS.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RDSEndpoint