trigger:
- master

variables:
- group: Deploy

jobs:
  - job: WaitForValidation
    pool: server
    steps:
    - task: ManualValidation@0
      continueOnError: false
      enabled: true
      timeoutInMinutes: 30
      inputs:
        notifyUsers: |
          gmoore@makpar.com
        instructions: 'Validate and approve infrastructure configuration before deployment'
        onTimeout: 'reject'

  - deployment: DeployInnoLab
    dependsOn: WaitForValidation
    displayName: Deploy Innovation Lab Cloud Resources
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'AWS'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              pip install -r ./src/requirements.txt
            displayName: Install deployment dependencies
          - script: |
              python ./src/deploy/deployer.py
            displayName: Deploy cloud resources
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              HOSTED_ZONE_ID: $(HOSTED_ZONE_ID)
              CERTIFICATE_ID: $(CERTIFICATE_ID)
