trigger:
- master

variables:
- group: Deploy

jobs:
  - job: ScanForVulnerabilities
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        displayName: Install Node version manager
      - script: |
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          npm install snyk -g
          snyk config set org=$SNYK_ORG_ID
        displayName: Install Node and SNYK CLI scanner
        env:
          NODE_VERSION: 14.0.0
          SNYK_TOKEN: $(SNYK_TOKEN)
          SNYK_ORG_ID: $(SNYK_ORG_ID)
      - script: |
          ./scripts/scan
        displayName: Scan templates for vulnerabilities

  - job: WaitForValidation
    dependsOn: ScanForVulnerabilities
    pool: server
    steps:
    - task: ManualValidation@0
      continueOnError: false
      enabled: true
      timeoutInMinutes: 30
      inputs:
        notifyUsers: |
          gmoore@makpar.com
        instructions: 'Validate and approve infrastructure configuration before deployment'
        onTimeout: 'reject'

  - deployment: DeployInnoLab
    dependsOn: WaitForValidation
    displayName: Deploy Innovation Lab Cloud Resources
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'AWS'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              pip install -r ./src/requirements.txt
            displayName: Install deployment dependencies
          - script: |
              python ./src/deploy/deployer.py
            displayName: Deploy cloud resources
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              HOSTED_ZONE_ID: $(HOSTED_ZONE_ID)
              CERTIFICATE_ID: $(CERTIFICATE_ID)
