trigger:
- master

variables:
- group: Dev

pool:
  vmImage: ubuntu-latest

jobs:
  - job: WaitForValidation
    pool: server
    steps:
    - task: ManualValidation@0
      continueOnError: false
      enabled: true
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: |
          gmoore@makpar.com
          tislam@makpar.com
          skonur@makpar.com
          nsibley@makpar.com
        instructions: 'Validate and approve infrastructure configuration before deployment'
  - job: DeployCloudResources
    steps:
    - script: pip install -r requirements.txt
      displayName: Install deployment dependencies
    - script: |
        python ./src/deploy/deployer.py
      displayName: Deploy cloud resources
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
