# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Dev


pool:
  vmImage: ubuntu-latest

steps:
- script: pip install -r requirements.txt
  displayName: Install deployment dependencies

- script: |
    printenv
    echo $AWS_ACCOUNT_ID
    export AWS_ACCOUNT_ID
    export AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY
    export AWS_DEFAULT_REGION
    python ./deploy/deployer.py
  displayName: Deploy cloud resources
