# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Dev


pool:
  vmImage: ubuntu-latest

steps:
- script: printenv
  displayName: 'Debug'

- script: |
    python ./deploy/deployer.py
  displayName: 'Install AWS CLI'
