# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Dev


pool:
  vmImage: ubuntu-latest

steps:
- task: ManualValidation@0
  continueOnError: false
  enabled: true
  inputs:
    notifyUsers: 'gmoore@makpar.com,tislam@makpar.com,skonur@makpar.com,nsibley@makpar.com'
- task: ManualValidation@0
  inputs:
    notifyUsers: 'gmoore@makpar.com,tislam@makpar.com,skonur@makpar.com,nsibley@makpar.com'
    instructions: 'Validate and approve infrastructure configuration before deployment'

- script: pip install -r requirements.txt
  displayName: Install deployment dependencies

- script: |
    python ./deploy/deployer.py
  displayName: Deploy cloud resources
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
