trigger:
- master

variables:
- group: Deploy

jobs:
  - job: ScanForVulnerabilities
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          npm install snyk -g
          npm -v
          snyk config set org=$SNYK_ORG_ID
          snyk auth $SNYK_TOKEN
          snyk --version
        displayName: Install SNYK CLI scanner
        env:
          NODE_VERSION: 14.0.0
          SNYK_TOKEN: $(SNYK_TOKEN)
          SNYK_ORG_ID: $(SNYK_ORG_ID)
          SNYK_SEVERITY: high
      - script: |
          ./scripts/scan
        displayName: Scan templates for vulnerabilities

  - job: WaitForValidation
    dependsOn: ScanForVulnerabilities
    pool: server
    steps:
    - task: ManualValidation@0
      continueOnError: false
      enabled: true
      timeoutInMinutes: 30
      inputs:
        notifyUsers: |
          gmoore@makpar.com
        instructions: 'Validate and approve infrastructure configuration before deployment'
        onTimeout: 'reject'

  - deployment: DeployInnoLab
    dependsOn: WaitForValidation
    displayName: Deploy Innovation Lab Cloud Resources
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'AWS'
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: |
              pip install -r ./src/requirements.txt
            displayName: Install deployment dependencies
          - script: |
              python ./src/deploy/deployer.py
            displayName: Deploy cloud resources
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              HOSTED_ZONE_ID: $(HOSTED_ZONE_ID)
              CERTIFICATE_ID: $(CERTIFICATE_ID)
