# This configuration YML is used within the *innolab-cloudformation* pipeline to determine which stacks it should update when changes are pushed to the master branch. 

iam-stack:

repo-stack:

vpc-stack:
  environment: Dev
  keygen: false
  bastion-host: true

rds-stack:
  environment: Dev
  type: postgres
  port: 5432

rds-stack: 
  environment: Dev
  type: oracle
  port: 1521

alation-stack:
  keygen: false

