## Innovation Lab Deployment Configuration
#   This configuration YML is used within the *innolab-cloudformation* pipeline to determine
#   which stacks it should update or create when changes are pushed to the master branch.
#
#   The *AWS* infrastructure itself is provisioned through a *Azure DevOps* pipeline subject to
#   to team lead and project owner approval. This pipeline will deploy or update the *AWS*
#   environment based on the configuration of this file. Note: this includes provisioning 
#   the *AWS CodePipelines* that actually deploys the applications. In other words, the 
#   *Azure Devops* pipeline is a "pipeline of pipelines".

## Syntax:
#   StackName:
#       template: <templateFile>
#       parameters:
#         - ParameterKey: <templateParameter> 
#           ParameterValue: value | !env <environmentVariable>
#         - ParameterKey: <templateParameter>
#           ParameterValue: value | !env <environmentVariable>
#         ...

## NOTES
# 1. The order of stacks *matters*! The stacks will be provisioned in the order they are listed.
#     If a stack requires resources from another stack, make sure the independent stack is deployed
#     before the dependent stack!

Innolab-IAMStack:
  template: iam.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: masterPassword
      ParameterValue: !env MASTER_PASSWORD
    - ParameterKey: pipelineUser
      ParameterValue: !env PIPELINE_USER

Innolab-RepoStack:
  template: repo.yml
  parameters: 
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: github
      ParameterValue: "false"

Innolab-VPCStack-Dev:
  template: vpc.yml
  parameters:
    - ParameterKey: applicationName 
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: dbKeyName
      ParameterValue: innolab_tunnel_key_Dev
    - ParameterKey: bastionHost
      ParameterValue: "true"

Innolab-PostgresRDSStack-Dev:
  template: rds.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: type
      ParameterValue: postgres
    - ParameterKey: port
      ParameterValue: "5432"
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack

Innolab-OracleRDSStack-Dev: 
  template: rds.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: type
      ParameterValue: oracle
    - ParameterKey: port
      ParameterValue: "1521"
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack

Innolab-AlationStack:
  template: applications/alation.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev 
    - ParameterKey: alationKeyName
      ParameterValue: innolab_alation_key
    - ParameterKey: domain
      ParameterValue: makpar-innovation.net
    - ParameterKey: hostedZoneId
      ParameterValue: !env HOSTED_ZONE_ID
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev

Innolab-MigrationStack:
  template: applications/migration.yml
  parameter:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: dbSourceUserName
      ParameterValue: !env ORACLE_RDS_USERNAME
    - ParameterKey: dbSourcePassword
      ParameterValue: !env ORACLE_RDS_PASSOWRD
    - ParameterKey: dbSourcePort
      ParameterValue: "5432"
    - ParameterKey: dbSourceDatabase
      ParameterValue: ORCL
    - ParameterKey: dbSourceEngine
      ParameterValue: oracle
    - ParameterKey: dbTargetUserName
      ParameterValue: !env POSTGRES_RDS_USERNAME
    - ParameterKey: dbTargetPassword
      ParameterValue: !env POSTGRES_RDS_PASSWORD
    - ParameterKey: dbTargetPort
      ParameterValue: "5432"
    - ParameterKey: dbTargetDatabase
      ParameterValue: postgres
    - ParameterKey: dbTargetEngine
      ParameterValue: postgres
    # TODO: update this once the postgres stack is deployed with new naming convention
    - ParameterKey: targetStack
      ParameterValue: Innolab-RDSStack-Dev
    - ParameterKey: sourceStack
      ParameterValue: Innolab-OracleRDSStack-Dev
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev

Innolab-LambdaStack-Dev:
  template: lambda.yml
  parameters:
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: cognitoStack 
      ParameterValue: Innolab-CognitoStack-Dev
    - ParameterKey: repoStack
      ParameterValue: Innolab-RepoStack
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: domainName
      ParameterValue: makpar-innovation.net
    - ParameterKey: hostedZoneId
      ParameterValue: !env HOSTED_ZONE_ID
    - ParameterKey: certificateId
      ParameterValue: !env CERTIFICATE_ID

# TODO: configure pipeline stacks
  
