## Innovation Lab Deployment Configuration
#   This configuration YML is used within the *innolab-cloudformation* pipeline to determine
#   which stacks it should update or create when changes are pushed to the master branch. 

## Syntax:
#   StackName:
#       template: <templateFile>
#       parameters:
#         - ParameterKey: <templateParameter> 
#           ParameterValue: value | !env <environmentVariable>
#         - ParameterKey: <templateParameter>
#           ParameterValue: value | !env <environmentVariable>
#         ...

## NOTES
# 1. The order of stacks *matters*! The stacks will be provisioned in the order they are listed.
#     If a stack requires resources from another stack, make sure the independent stack is deployed
#     before the dependent stack!

Innolab-IAMStack:
  template: iam.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: masterPassword
      ParameterValue: !env MASTER_PASSWORD
    - ParameterKey: pipelineUser
      ParameterValue: !env PIPELINE_USER
    - ParameterKey: bitbucket
      ParameterValue: false

Innolab-RepoStack:
  template: repo.yml
  parameters: 
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: github
      ParameterValue: false

Innolab-CognitoStack-Dev:
  template: cognito.yml
  parameters:
    - ParameterKey:
      ParameterValue:

Innolab-VPCStack-Dev:
  template: vpc.yml
  parameters:
    - ParameterKey: applicationName 
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: dbKeyName
      ParameterValue: innolab_tunnel_key_Dev
    - ParameterKey: bastionHost
      ParameterValue: true

Innolab-RDSStack-Dev:
  template: rds.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: type
      ParameterValue: postgres
    - ParameterKey: port
      ParameterValue: 5432
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack

Innolab-OracleRDSStack-Dev: 
  template: rds.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environment
      ParameterValue: Dev
    - ParameterKey: type
      ParameterValue: oracle
    - ParameterKey: port
      ParameterValue: 1521
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack

Innolab-AlationStack-Dev:
  template: applications/alation.yml
  parameters:
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev 
    - ParameterKey: alationKeyName
      ParameterValue: alation_key
    - ParameterKey: domain
      ParameterValue: makpar-innovation.net
    - ParameterKey: hostedZoneId
      ParameterValue: !env HOSTED_ZONE_ID
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev

Innolab-LambdaStack-Dev:
  template: lambda.yml
  parameters:
    - ParameterKey: iamStack
      ParameterValue: Innolab-IAMStack
    - ParameterKey: vpcStack
      ParameterValue: Innolab-VPCStack-Dev
    - ParameterKey: cognitoStack 
      ParameterValue: Innolab-CognitoStack-Dev
    - ParameterKey: repoStack
      ParameterValue: Innolab-RepoStack
    - ParameterKey: environmentName
      ParameterValue: Dev
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: domainName
      ParameterValue: makpar-innovation.net
    - ParameterKey: hostedZoneId
      ParameterValue: !env HOSTED_ZONE_ID
    - ParameterKey: certificateId
      ParameterValue: !env CERTIFICATE_ID

Innolab-DynamoStack-Dev:
  template: dynamo.yml
  parameters:
    - ParameterKey: tableName
      ParameterValue: CommitTable
    - ParameterKey: partitionKey
      ParameterValue: commit_hash
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev

Innolab-CognitoStack-Dev:
  template: cognito.yml
  parameters:
    - ParameterKey: domainName
      ParameterValue: makpar-innovation.net
    - ParameterKey: applicationName
      ParameterValue: innolab
    - ParameterKey: environmentName
      ParameterValue: Dev

  
