# This configuration YML is used within the *innolab-cloudformation* pipeline to determine which stacks it should update when changes are pushed to the master branch. 

# SYNTAX:

# StackName:
#     template: <templateFile>
#     <templateParameter>: value | !env <environmentVariable>
#     <templateParameter>: value | !env <environmentVariable>
#     ...

Innolab-IAMStack:
  template: iam.yml
  applicationName: innolab
  masterPassword: !env MASTER_PASSWORD
  pipelineUser: !env PIPELINE_USER
  bitbucket: false

Innolab-RepoStack:
  template: repo.yml
  applicationName: innolab
  github: false

Innolab-VPCStack-Dev:
  template: vpc.yml
  applicationName: innolab
  environmentName: Dev
  dbKeyName: innolab_tunnel_key_Dev
  bastionHost: true

Innolab-Postgres-RDSStack-Dev:
  template: rds.yml
  applicationName: innolab
  environmentName: Dev
  type: postgres
  port: 5432
  vpcStack: Innolab-VPCStack-Dev
  iamStack: Innolab-IAMStack

Innolab-Oracle-RDSStack-Dev: 
  template: rds.yml
  applicationName: innolab
  environment: Dev
  type: oracle
  port: 1521
  vpcStack: Innolab-VPCStack-Dev
  iamStack: Innolab-IAMStack

Innolab-AlationStack-Dev:
  template: applications/alation.yml
  applicationName: innolab
  environmentName: Dev
  alationKeyName: alation_key
  domain: makpar-innovation.net
  hostedZoneId: !env HOSTED_ZONE_ID
  vpcStack: Innolab-VPCStack-Dev
  
