AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  vpcStack:
    Type: String
    Default: Innolab-VPCStack-Dev
  alationKeyName: 
    Type: String
    Default: alation_key
  applicationName:
    Type: String
    Default: innolab

Description: "Configuration and resources for deploying Alation service into ${applicationName}-VPCStack-Dev"


Resources:
  Alation:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0b0af3577fe5e3532"
      InstanceType: "t3.2xlarge"
      KeyName: !Ref alationKeyName
      AvailabilityZone: !Sub "${AWS::Region}b"
      Tenancy: "default"
      ## NOTE: Uncomment below to deploy into Private Subnet.
      ######################################
      # SubnetId: 
      #   Fn::ImportValue: !Sub "${vpcStack}-PrivateSubnetB"
      # SecurityGroupIds: 
      #   - Fn::ImportValue:
      #       !Sub "${vpcStack}-DatabaseSecurityGroup"
      ######################################
      ## NOTE: Uncomment below to deploy into Public Subnet.
      ######################################
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: 
            Fn::ImportValue: !Sub "${vpcStack}-PublicSubnetB"
          AssociatePublicIpAddress: true
          GroupSet: [Fn::ImportValue: !Sub "${vpcStack}-NATSecurityGroup", !Ref AlationSecurityGroup]  
      #######################################
      EbsOptimized: true
      SourceDestCheck: true
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            Encrypted: false
            VolumeSize: 1000
            VolumeType: "gp2"
            DeleteOnTermination: true
      IamInstanceProfile: !Ref AlationRole
      Tags: 
        - Key: Name
          Value: !Sub ${applicationName}-Dev-alation 
        - Key: "Environment"
          Value: "Dev"
        - Key: "Application"
          Value: "innolab"
      HibernationOptions: 
        Configured: false
      CpuOptions: 
        CoreCount: 4
        ThreadsPerCore: 2
      EnclaveOptions: 
        Enabled: false
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          TOKEN=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id innolab-alationToken --query SecretString --output text)
          dnf install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
          dnf install -y https://s3.us-east-1.amazonaws.com/amazoncloudwatch-agent-us-east-1/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
          cd /home/
          curl -kLH "Authorization: Token $TOKEN" https://customerportal.alationdata.com/api/build_artifact/13195/download/ > alation-2022.1-11.2.2.159547.rpm
          rpm -i alation-2022.1-11.2.2.159547.rpm
          mkdir /home/main
          mkdir /home/backup
          /etc/init.d/alation init /home/main/ /home/backup/
          /etc/init.d/alation start

  AlationRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: "AlationEC2Role"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      Policies:
        - PolicyName: !Sub ${applicationName}-alation-secret-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SecretManagerPermissions
                Action: 
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${applicationName}-*"
      Description: "Role for Alation EC2 to access other services"
      Tags:
        - Key: "Application"
          Value: "innolab"
        - Key: "Environment"
          Value: "Dev"

  AlationInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: !Sub "${applicationName}-alation-instance-profile"
      Roles: 
        - !Ref AlationRole

  AlationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${applicationName}-alation-security-group
      GroupDescription: Allow internet ingress into Alation
      VpcId: 
        Fn::ImportValue: !Sub ${vpcStack}-VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

