AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a DB subnet group and postgres Database"

Parameters:
  vpcStack:
    Type: String
    Default: CCC-VPCStack-Dev

  environmentName:
    Type: String
    Default: Dev

Resources:
    PostgresRDS:
        Type: AWS::RDS::DBInstance
        Properties:
            DBInstanceIdentifier: aws-dxl-database-1
            AllocatedStorage: 100
            DBInstanceClass: db.t3.micro
            Engine: "postgres"
            MasterUsername: !Sub "{{resolve:ssm-secure:/CCC/credentials/${environmentName}/dbUsername:1}}"
            MasterUserPassword: !Sub "{{resolve:ssm-secure:/CCC/credentials/${environmentName}/dbPassword:1}}"
            BackupRetentionPeriod: 7
            MultiAZ: true
            EngineVersion: 8.0.20
            AutoMinorVersionUpgrade: true
            Iops: 1000
            PubliclyAccessible: false
            StorageType: io1
            Port: 3306
            StorageEncrypted: true
            CopyTagsToSnapshot: true
            MonitoringInterval: 60
            EnableIAMDatabaseAuthentication: false
            EnablePerformanceInsights: true
            PerformanceInsightsRetentionPeriod: 7
            DeletionProtection: true
            DBSubnetGroupName: Fn::ImportValue: !Sub ${vpcStack}-DatabaseSubnetGroup
            VPCSecurityGroups: 
              - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
            MaxAllocatedStorage: 1000
            MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
            Tags: 
              - Key: Environment
                Value: !Ref Dev
        DependsOn:
          - dbusername 
          - dbpassword