AWSTemplateFormatVersion: "2010-09-09"
Description: "Provisions a DB instances with credentials resolved from the SSM parameter store. Note: the credentials must exist in the parameter store before this template is inputted into CloudFormation"

Parameters:
  vpcStack:
    Type: String
    Default: CCC-VPCStack-Dev

  dbUsername:
    Type: String
    Default: WilliamFaulkner

  environmentName:
    Type: String
    Default: Dev

Resources:
    PostgresRDS:
      Type: AWS::RDS::DBInstance
      Properties:
          DBInstanceIdentifier: !Sub CCC-Database-${environmentName}
          AllocatedStorage: 100
          DBInstanceClass: db.t3.micro
          Engine: "postgres"
          MasterUsername: !Ref dbUsername
          MasterUserPassword: !Sub "{{resolve:ssm-secure:/CCC/credentials/${environmentName}/dbPassword:1}}"
          BackupRetentionPeriod: 7
          MultiAZ: true
          AutoMinorVersionUpgrade: true
          Iops: 1000
          PubliclyAccessible: false
          StorageType: io1
          Port: 5432
          StorageEncrypted: true
          CopyTagsToSnapshot: true
          MonitoringInterval: 60
          EnableIAMDatabaseAuthentication: false
          EnablePerformanceInsights: true
          PerformanceInsightsRetentionPeriod: 7
          DeletionProtection: false
          DBSubnetGroupName: 
            Fn::ImportValue: !Sub ${vpcStack}-DatabaseSubnetGroup
          VPCSecurityGroups: 
            - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
          MaxAllocatedStorage: 1000
          MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
          Tags: 
            - Key: Environment
              Value: !Ref environmentName