AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a DB subnet group and postgres Database"

Parameters:
  MasterUsername:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The username for our database.
  
  MasterUserPassword:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The password for the database.
    "NoEcho": true

  vpcStack:
    Type: String
    Default: CCC-VPCStack-Dev

  environmentName:
    Type: String
    Default: Dev

Resources:
    dbusername:
      Type: AWS::SSM::Parameter
      Properties:
        Name: command
        Type: String
        Value: !Ref MasterUsername
        Description: SSM Parameter for running date command.
        AllowedPattern: "^[a-zA-Z]{1,10}$"
        Tags:
          Environment: !Ref environmentName
  
    dbpassword:
      Type: AWS::SSM::Parameter
      Properties:
        Name: command
        Type: String
        Value: !Ref MasterPassword
        Description: SSM Parameter for running date command.
        AllowedPattern: "^[a-zA-Z]{1,10}$"
        Tags:
          Environment: !Ref environmentName

    PostgresRDS:
        Type: AWS::RDS::DBInstance
        Properties:
            DBInstanceIdentifier: aws-dxl-database-1
            AllocatedStorage: 100
            DBInstanceClass: db.t3.micro
            Engine: "postgres"
            MasterUsername: !Ref MasterUsername
            MasterUserPassword: !Ref MasterUserPassword
            BackupRetentionPeriod: 7
            MultiAZ: true
            EngineVersion: 8.0.20
            AutoMinorVersionUpgrade: true
            Iops: 1000
            PubliclyAccessible: false
            StorageType: io1
            Port: 3306
            StorageEncrypted: true
            CopyTagsToSnapshot: true
            MonitoringInterval: 60
            EnableIAMDatabaseAuthentication: false
            EnablePerformanceInsights: true
            PerformanceInsightsRetentionPeriod: 7
            DeletionProtection: true
            DBSubnetGroupName: Fn::ImportValue: !Sub ${vpcStack}-DatabaseSubnetGroup
            VPCSecurityGroups: 
              - Fn::ImportValue:: !Sub ${vpcStack}-DatabaseSecurityGroup
            MaxAllocatedStorage: 1000
            DBParameterGroupName: !Ref ParameterGroup
            MonitoringRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role"
            Tags: 
              - Key: Environment
                Value: !Ref Dev
        DependsOn:
          - dbusername 
          - dbpassword