AWSTemplateFormatVersion: "2010-09-09"

Description: "A stack containing the resources to serve the CCC-Frontend-${ENV} assets. This stack will provision "

Parameters:
  domain:
    Type: String
    Default: ${AWS::NoValue}

Conditions:
  NoDomain: !Equals 
    - !Ref domain
    - ${AWS::NoValue}
  
  Domain: !Not
    - Condition: NoDomain
    
Resources:

  FrontendHostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "makpar-innovation.com."

  # NOTE: Need this if we have to setup our own domain
  # CertificateManagerCertificate:
    # Type: AWS::CertificateManager::Certificate
    # Properties:
      # DomainName: !Ref DomainName
      # ValidationMethod: DNS

  FrontendDeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub '${AWS::StackName}-deployment'
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketLogs
        LogFilePrefix: 'cdn/'
      WebsiteConfiguration:
        IndexDocument: 'index.html'

  DeployBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendDeployBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 's3:GetObject'
            Principal: '*'
            Resource: !Sub '${FrontendDeployBucket.Arn}/*'

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: 
        Aliases: 
        - "sad-dev.makpar-innovation.com"
        Origins: 
        - 
          ConnectionAttempts: 3
          ConnectionTimeout: 10
          DomainName: "mil-sec-analytics.s3.amazonaws.com"
          Id: "S3-mil-sec-analytics"
          OriginPath: ""
          S3OriginConfig: 
            OriginAccessIdentity: "origin-access-identity/cloudfront/E2J2G6UQUY8017"
        OriginGroups: 
          Quantity: 0
        DefaultCacheBehavior: 
          AllowedMethods: 
          - "HEAD"
          - "DELETE"
          - "POST"
          - "GET"
          - "OPTIONS"
          - "PUT"
          - "PATCH"
          CachedMethods: 
          - "HEAD"
          - "GET"
          Compress: false
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          SmoothStreaming: false
          TargetOriginId: "S3-mil-sec-analytics"
          ViewerProtocolPolicy: "redirect-to-https"
        Comment: ""
        PriceClass: "PriceClass_All"
        Enabled: true
        ViewerCertificate: 
          AcmCertificateArn: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/fb77f968-40f2-43ee-8261-1b22006b4bcd"
          MinimumProtocolVersion: "TLSv1.2_2019"
          SslSupportMethod: "sni-only"
        Restrictions: 
          GeoRestriction: 
            RestrictionType: "none"
        HttpVersion: "http2"
        DefaultRootObject: ""
        IPV6Enabled: true