AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  componentName:
    Type: String
  environmentName:
    Type: String
    Default: Dev
  userStack:
    Type: String
    Default: CCC-UserStack
  vpcStack:
    Type: String
    Default: CCC-VPCStack
  ecrStack:
    Type: String
    Default: CCC-ECRStack

Resources:
  LambdaECR:
    Type: AWS::ECR::Repository
    Description: ECR to hold image of Lambda function
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
        RepositoryName: !Sub lambda-${componentName}
    RepositoryPolicyText:
      Version: "2012-10-17"
      Statement:
        - Sid: ECRLambdaPolicy
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
              
  LambdaFunction:
    Type: AWS::Lambda::Function
    Description: Lambda function deployed into Production environment
    Properties:
      FunctionName: !Sub lambda-${componentName}-${environmentName}
      Code: !Sub ${LambdaECR.RepositoryUri}:${environmentName}
      PackageType: Image
      Role: !ImportValue ${userStack.LambdaExecutorArn}
    DependsOn: 
      - LambdaExectuor
      - LambdaECR
    VpcConfig:
      SecurityGroupIds: !ImportValue ${vpcStack.DatabaseSecurityGroupId}
      SubnetIds: 
        - !Join ["", [!ImportValue ${vpcStack.PrivateSubnetA}, !ImportValue ${vpcStack.PrivateSubnetB} ]]
