AWSTemplateFormatVersion: "2010-09-09"

Description: 'Conditionally provisions a series of Lambda functions, gives them an execution role for the VPC from CCC-VPCStack and attaches policies to update the function code to the pipeline user from the CCC-UserStack'

Parameters:
  components:
    Type: String
    AllowedValues:
      - one
      - two
      - three
      - four
    Default: four
  environmentName:
    Type: String
    Default: Dev
  userStack:
    Type: String
    Default: CCC-UserStack
  vpcStack:
    Type: String
    Default: CCC-VPCStack-Dev
  ecrStack:
    Type: String
    Default: CCC-ECRStack

Conditions:
  CreateOneComponent: !Equals
      - !Ref components
      - one
  CreateTwoComponents: !Equals
      - !Ref components
      - two
  CreateThreeComponents: !Equals
      - !Ref components
      - three
  CreateFourComponents: !Equals
      - !Ref components
      - four
  
  CreateAlphaComponent: !Or
    - !Condition CreateOneComponent
    - !Condition CreateTwoComponents
    - !Condition CreateThreeComponents
    - !Condition CreateFourComponents

  CreateBetaComponent: !Or
    - !Condition CreateTwoComponents
    - !Condition CreateThreeComponents
    - !Condition CreateFourComponents

  CreateGammaComponent: !Or
    - !Condition CreateThreeComponents
    - !Condition CreateFourComponents

  CreateDeltaComponent: !Condition CreateFourComponents

Resources:
  LambdaAlpha:
    Type: AWS::Lambda::Function
    Condition: CreateAlphaComponent
    Description: Lambda function alpha
    Properties:
      FunctionName: !Sub lambda-alpha-${environmentName}
      Code: 
        ImageUri: !Sub
          - "${ecrRepo}:${environment}"
          - ecrRepo: 
              Fn::ImportValue: !Sub ${ecrStack}-LambdaAlphaImageRepository
            environment: !Ref environmentName
      PackageType: Image
      Role: 
        Fn::ImportValue: !Sub ${userStack}-LambdaExecutorArn
      VpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetA
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetB
      Environment:
        Variables:
          POSTGRES_HOST: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbHost"
          POSTGRES_USER: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbUsername"
          POSTGRES_PASSWORD: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbPassword"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaAlpha

  LambdaBeta:
    Type: AWS::Lambda::Function
    Condition: CreateBetaComponent
    Description: Lambda beta function
    Properties:
      FunctionName: !Sub lambda-beta-${environmentName}
      Code: 
        ImageUri: !Sub
          - "${ecrRepo}:${environment}"
          - ecrRepo: 
              Fn::ImportValue: !Sub ${ecrStack}-LambdaBetaImageRepository
            environment: !Ref environmentName
      PackageType: Image
      Role: 
        Fn::ImportValue: !Sub ${userStack}-LambdaExecutorArn
      VpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
        SubnetIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetA
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetB
      Environment:
        Variables:
          POSTGRES_HOST: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbHost"
          POSTGRES_USER: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbUsername"
          POSTGRES_PASSWORD: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbPassword"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaBeta

  LambdaGamma:
    Type: AWS::Lambda::Function
    Condition: CreateGammaComponent
    Description: Lambda gamma function
    Properties:
      FunctionName: !Sub lambda-gamma-${environmentName}
      Code: 
        ImageUri: !Sub
          - "${ecrRepo}:${environment}"
          - ecrRepo: 
              Fn::ImportValue: !Sub ${ecrStack}-LambdaGammaImageRepository
            environment: !Ref environmentName
      PackageType: Image
      Role: 
        Fn::ImportValue: !Sub ${userStack}-LambdaExecutorArn
      VpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
        SubnetIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetA
          - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetB
      Environment:
        Variables:
          POSTGRES_HOST: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbHost"
          POSTGRES_USER: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbUsername"
          POSTGRES_PASSWORD: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbPassword"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaGamma

  LambdaDelta:
    Type: AWS::Lambda::Function
    Condition: CreateDeltaComponent
    Description: Lambda Delta function
    Properties:
      FunctionName: !Sub lambda-delta-${environmentName}
      Code: 
        ImageUri: !Sub
          - "${ecrRepo}:${environment}"
          - ecrRepo: 
              Fn::ImportValue: !Sub ${ecrStack}-LambdaDeltaImageRepository
            environment: !Ref environmentName
      PackageType: Image
      Role: 
        Fn::ImportValue: !Sub ${userStack}-LambdaExecutorArn
      VpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${vpcStack}-DatabaseSecurityGroup
        SubnetIds: 
            - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetA
            - Fn::ImportValue: !Sub ${vpcStack}-PrivateSubnetB
      Environment:
        Variables:
          POSTGRES_HOST: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbHost"
          POSTGRES_USER: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbUsername"
          POSTGRES_PASSWORD: !Sub "{{resolve:ssm:/CCC/credentials/${environmentName}/dbPassword"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaDelta

  PipelineLambdaPolicy:
    Type: AWS::IAM::Policy
    Description: Policy to allow pipeline to update Lambda functions
    Properties:
      PolicyName: !Sub pipeline-lambda-${environmentName}-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: UpdateLambdaFunction
            Effect: Allow
            Action: 
              - "lambda:UpdateFunctionCode"
            Resource:
              - !GetAtt LambdaGamma.Arn
              - !GetAtt LambdaDelta.Arn
              - !GetAtt LambdaBeta.Arn
              - !GetAtt LambdaAlpha.Arn
      Users: 
        - Fn::ImportValue: !Sub ${userStack}-PipelineUserName
    DependsOn:
      - LambdaGamma
      - LambdaDelta
      - LambdaBeta
      - LambdaAlpha

Outputs:
  LambdaAlphaArn:
    Value: !GetAtt LambdaAlpha.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaAlphaArn
  LambdaBetaArn:
    Value: !GetAtt LambdaBeta.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaBetaArn
  LambdaGamma:
    Value: !GetAtt LambdaGamma.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaGammaArn
  LambdaDelta:
    Value: !GetAtt LambdaDelta.Arn
    Export: 
      Name: !Sub ${AWS::StackName}-LambdaDeltaArn