AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  component:
    Type: String

Resources:
  LambdaECR:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
        RepositoryName: !Sub lambda-${component}
    RepositoryPolicyText:
      Version: "2012-10-17"
      Statement:
          - Sid: ECRLambdaPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
              Action:
                - "ecr:BatchGetImage"
                - "ecr:GetDownloadUrlForLayer"

  LambdaExecutor:
    Type: AWS::IAM::Role
    Description: Allows Lambda to access other AWS Services
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: 
                - "sts:AssumeRole"
              
  LambdaFunctionProduction:
    Type: AWS::Lambda::Function
    Description: Lambda function deployed into Production
    Properties:
      FunctionName: !Sub lambda-${component}_master
      Code: !Sub ${LambdaECR.RepositoryUri}:master
      PackageType: Image
      Role: !GetAtt LambdaExecutor.Arn
  
  LambdaFunctionDevelopment:
    Type: AWS::Lambda::Function
    Description: Lambda function deployed into Development
    Properties:
      FunctionName: !Sub lambda-${component}_development
      Code: !Sub ${LambdaECR.RepositoryUri}:development
      Role: !GetAtt LambdaExecutor.Arn
  
  LambdaFunctionTest:
    Type: AWS::Lambda::Function
    Description: Lambda function deployed into Development
    Properties:
      FunctionName: !Sub lambda-${component}_test
      Code: !Sub ${LambdaECR.RepositoryUri}:test
      Role: !GetAtt LambdaExecutor.Arn

