AWSTemplateFormatVersion: '2010-09-09'

Description: 'Creates dummy account for pipeline, execution role for Lambda, and other IAM resources'

Parameters:
  pipelineUser:
    Type: String
    Default: ccc-pipeline

Resources:
  PipelineUser:
    Type: AWS::IAM::User
    Description: User account for pipeline to perform all the necessary actions
    Properties:
      UserName: !Ref pipelineUser

  LambdaExecutor:
    Type: AWS::IAM::Role
    Description: Allows Lambda to access other AWS Services
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  PipelineUserArn:
    Value: !GetAtt PipelineUser.Arn
  LambdaExecutorArn:
    Value: !GetAtt LambdaExecutor.Arn