AWSTemplateFormatVersion: '2010-09-09'

Description: 'A stack containing a dummy account for pipeline, execution role for Lambda, and other IAM resources needed for the comet-code-challenge'

Parameters:
  pipelineUser:
    Type: String
    Default: ccc-pipeline

Resources:
  PipelineUser:
    Type: AWS::IAM::User
    Description: User account for CCC pipeline to perform all the necessary deployment operations
    Properties:
      UserName: !Ref pipelineUser

  LambdaExecutor:
    Type: AWS::IAM::Role
    Description: Role to allow CCC Lambdas to access other AWS Services
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  PipelineUserArn:
    Value: !GetAtt PipelineUser.Arn
    Description: ARN for BitBucket Pipeline User
    Export:
      Name: !Sub ${AWS::StackName}-PipelineUserArn
  PipelineUserName:
    Value: !Ref pipelineUser
    Description: Username for BitBucket Pipeline User
    Export:
      Name: !Sub ${AWS::StackName}-PipelineUserName
  LambdaExecutorArn:
    Value: !GetAtt LambdaExecutor.Arn
    Description: ARN for Lambda Execution Role
    Export:
      Name: !Sub ${AWS::StackName}-LambdaExecutorArn