AWSTemplateFormatVersion: '2010-09-09'

Description: "A stack for provisioning the CodeCommit repositories where the application source code will be housed and S3 buckets that will hold application artifacts."

Parameters:
  applicationName:
    Type: String
    Default: innolab

Resources:
  DocumentationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub "${applicationName}-documentation"
      
  CredentialsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub "${applicationName}-credentials"
  
  PostgresECR:
    Type: AWS::ECR::Repository
    Description: ECR to hold image of Postgres image
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-postgres"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ecr-code-build-policy
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"

  LambdaAlphaECR:
    Type: AWS::ECR::Repository
    Condition: CreateAlphaComponent
    Description: ECR to hold image of Lambda function
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-lambda-alpha"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ECRLambdaPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaAlphaECR

  LambdaBetaECR:
    Type: AWS::ECR::Repository
    Condition: CreateBetaComponent
    Description: ECR to hold image of Lambda beta function
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-lambda-beta"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ECRLambdaBetaPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaBetaECR
  
  LambdaGammaECR:
    Type: AWS::ECR::Repository
    Condition: CreateAlphaComponent
    Description: ECR to hold image of Lambda gamma function
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-lambda-gamma"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ECRLambdaGammaPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaGammaECR

  LambdaDeltaECR:
    Type: AWS::ECR::Repository
    Condition: CreateDeltaComponent
    Description: ECR to hold image of Lambda Delta function
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-lambda-delta"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ECRLambdaDeltaPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaDeltaECR

  LambdaEpsilonECR:
    Type: AWS::ECR::Repository
    Condition: CreateEpsilonComponent
    Description: ECR to hold image of Lambda Epsilon function
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub "${applicationName}-lambda-epsilon"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: ECRLambdaEpsilonPolicy
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaEpsilonECR

  DockerRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-docker-images"
      RepositoryDescription: "A repository for Dockerfiles"

  CloudFormationRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-cloudformation"
      RepositoryDescription: "A repository for CloudFormation templates"

  FrontendRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-frontend"
      RepositoryDescription: "A repository for the frontend application"

  LambdaRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-lambdas"
      RepositoryDescription: "A repository for Lambda functions"
      
  BackendRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-backend"
      RepositoryDescription: "A repository for the backend application"
      
  TestingRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${applicationName}-test-harness"
      RepositoryDescription: "A repository for the BDD testing harness"

Outputs:
  DockerRepository:
    Value: !GetAtt DockerRepo.Name
    Description: Repository name for Dockerfile repository
    Export:
      Name: !Sub ${AWS::StackName}-DockerRepository
  DockerRepositoryARN:
    Value: !GetAtt DockerRepo.Arn
    Description: Repository ARN for Dockerfile repository
    Export:
      Name: !Sub ${AWS::StackName}-DockerRepositoryARN
  DockerRepositorySSHClone:
    Value: !GetAtt DockerRepo.CloneUrlSsh
    Description: SSH clone URL for Dockerfile repository
    Export:
      Name: !Sub ${AWS::StackName}-DockerCloneSSH

  CloudFormationRepository:
    Value: !GetAtt CloudFormationRepo.Name
    Description: Repository name for CloudFormation template repository
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationRepository
  CloudFormationRepositorySSHClone:
    Value: !GetAtt CloudFormationRepo.CloneUrlSsh
    Description: SSH clone URL for CloudFormation template repository
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationCloneSSH
  CloudFormationRepositoryARN:
    Value: !GetAtt CloudFormationRepo.Arn
    Description: Repository ARN for CloudFormation template repository
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationARN

  FrontendRepository:
    Value: !GetAtt FrontendRepo.Name
    Description: Repository name for the Frontend React app repository
    Export:
      Name: !Sub ${AWS::StackName}-FrontendRepository
  FrontendRepositoryARN:
    Value: !GetAtt FrontendRepo.Arn
    Description: Repository ARN for the Frontend React app repository
    Export:
      Name: !Sub ${AWS::StackName}-FrontendRepositoryARN
  FrontendRepositorySSHClone:
    Value: !GetAtt FrontendRepo.CloneUrlSsh
    Description: Repository name for the Frontend React app repository
    Export:
      Name: !Sub ${AWS::StackName}-FrontendCloneSSH

  BackendRepository:
    Value: !GetAtt BackendRepo.Name
    Description: Repository name for Backend Lambda function repository
    Export:
      Name: !Sub ${AWS::StackName}-BackendRepository
  BackendRepositoryARN:
    Value: !GetAtt BackendRepo.Arn
    Description: Repository name for Backend Lambda function repository
    Export:
      Name: !Sub ${AWS::StackName}-BackendRepositoryARN
  BackendCloneSSH:
    Value: !GetAtt BackendRepo.CloneUrlSsh
    Description: SSH clone URL for Backend Lambda function repository
    Export:
      Name: !Sub ${AWS::StackName}-BackendCloneSSH

  TestingRepository:
    Value: !GetAtt TestingRepo.Name
    Description: Repository name for automated testing repository
    Export:
      Name: !Sub ${AWS::StackName}-TestingRepository
  TestingRepositoryARN:
    Value: !GetAtt TestingRepo.Arn
    Description: Repository name for automated testing repository
    Export:
      Name: !Sub ${AWS::StackName}-TestingRepositoryARN
  TestingCloneSSH:
    Value: !GetAtt TestingRepo.CloneUrlSsh
    Description: Repository name for automated testing repository
    Export:
      Name: !Sub ${AWS::StackName}-TestingCloneSSH

  PostgresECRRepository:
    Value: !GetAtt PostgresECR.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-PostgresECR
  LambdaAlphaImageRepository:
    Value: !GetAtt LambdaAlphaECR.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-LambdaAlphaImageRepository
  LambdaBetaImageRepository:
    Value: !GetAtt LambdaBetaECR.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-LambdaBetaImageRepository
  LambdaGammaImageRepository:
    Value: !GetAtt LambdaGammaECR.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-LambdaGammaImageRepository
  LambdaDeltaImageRepositry:
    Value: !GetAtt LambdaDeltaECR.RepositoryUri
    Export: 
      Name: !Sub ${AWS::StackName}-LambdaDeltaImageRepository
  LambdaEpsilonImageRepository:
    Value: !GetAtt LambdaEpsilonECR.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-LambdaEpsilonImageRepository