AWSTemplateFormatVersion: '2010-09-09'

Description: 'A stack containing a dummy account for pipeline, execution role for Lambda, and other IAM resources needed for the comet-code-challenge'

Parameters:
  username:
    Type: String

  password:
    Type: String
  
  type:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - DevOps
      - DBA
      - Admin

Conditions:

  Admin: !Equals
    - !Ref type
    - Admin

  Developer: !Equals 
    - !Ref type
    - Dev

  DevOps: !Equals
    - !Ref type
    - DevOps
  
  DatabaseAdmin: !Equals
    - !Ref type
    - DBA

Resources:
  DevOpsUser:
    Type: AWS::IAM::User
    Condition: DevOps
    Properties:
      LoginProfile:
        Password: !Ref password
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Path: /ccc
      UserName: !Ref username
  
  DevOpsAccessKey:
    Type: AWS::IAM::AccessKey
    Condition: DevOps
    Properties: 
      UserName: !Ref DevOpsUser
    DependsOn:
      - DevOpsUser

  AdminUser:
    Type: AWS::IAM::User
    Condition: Admin
    Properties:
      LoginProfile:
        Password: !Ref password
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /ccc
      UserName: !Ref username

  AdminAccessKey:
    Type: AWS::IAM::AccessKey
    Condition: Admin
    Properties: 
      UserName: !Ref Admin
    DependsOn:
      - AdminUser

  DeveloperUser:
    Type: AWS::IAM::User
    Condition: Developer
    Properties:
      LoginProfile:
        Password: !Ref password
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
        - arn:aws:iam::aws:policy/CloudFrontFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Path: /ccc
      UserName: !Ref username

  DeveloperAccessKey:
    Type: AWS::IAM::AccessKey
    Condition: Developer
    Properties: 
      UserName: !Ref DeveloperUser
  
  DatabaseAdmin:
    Type: AWS::IAM::User
    Condition: DatabaseAdmin
    Properties:
      LoginProfile:
        Password: !Ref password
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Path: /ccc
      UserName: !Ref username